README.md, clap.zig, clap/comptime.zig, clap/streaming.zig, example/README.md.template, example/comptime-clap.zig, example/simple.zig, example/streaming-clap.zig
Hi again!
I'm proposing supporting multiple/repeated value-taking options. My use case is enabling extensions with a syntax like `-e, --extension <EXTENSION>` where the option can be specified multiple times to enable multiple extensions.
A sample implementation is attached which preserves the existing API while extending it to support multiple options. I use it like this:
```zig
for (args.allOptions("--extension")) |extension|
std.debug.print("enabling {}\n", .{extension});
```
We might want to make it explicitly opt-in (e.g. by requiring a declaration like `-e, --extension <EXTENSION>...`). What do you think?
=> parse multiple options

README.md, clap.zig, clap/comptime.zig, clap/streaming.zig, example/comptime-clap.zig, example/simple-error.zig, example/simple.zig, example/streaming-clap.zig
This is the work that will close #6. Right now the new `Diagnostic` struct only contains a `Names` struct that will either contain the `param.names` in cases where there was an error parsing a specific parameter, or the name of an argument in case the argument doesn't match any parameter. I'll need to also create a function on `Diagnostic` called `report` that will be the default way of reporting a parsing error to a stream.
=> Report error context in Diagnostic

README.md, build.zig, clap.zig, clap/streaming.zig, example/help.zig, example/simple-ex.zig, example/simple.zig, example/streaming-clap.zig, example/usage.zig
`outStream`s deprecated for `writer`s, and now `{s}` is required to format `[]u8` as a string.
=> zig master updates

README.md, clap.zig, clap/comptime.zig, clap/streaming.zig, example/simple-ex.zig, example/simple.zig, example/streaming-clap.zig
This allows for default arguments, which we can also extend without
breaking peoples code in the future. This is a breaking change right now
though.
=> Refactor Diagnostic (and others) into a ParseOption struct

README.md, example/usage.zig
There was a small typo in the `usage` example that listed two params as "version"
=> Update example of `usage`

.github/workflows/main.yml, clap/comptime.zig
This PR is meant to implement #47 since it seems inactive and is merging into the wrong branch. All this does is discard an unused variable since those are compiler errors now. I also went ahead and changed the `zig-master` CI to use `master` instead of `0.8.0`. If the latter change wasn't wanted I can go ahead and revert it.
=> Update zig-master branch

clap.zig
The tokenize function was made generic, so we have to pass the type as
the first parameter.
=> Update calls to tokenizer

clap.zig
Implements https://github.com/Hejsil/zig-clap/issues/28#issuecomment-913076259
The only change necessary for the `zig-master` branch would be to update the `mem.split(help_text, "\n");` call to `mem.split(u8, help_text, "\n");`. I will submit a followup PR for that branch if this is merged.
=> Indent help text on every new line to allow for user-controlled wrapping

README.md, example/README.md.template, example/help.zig, example/usage.zig
Instead of just calling these function, have the examples be small
programs that demonstrates how you would actually use them together with
argument parsing.
fixes #57
=> Improve help and usage examples

README.md, clap.zig, example/README.md.template, example/help.zig
New `help` function that is significantly more powerful and should be extendable without any more breaking changes to it. By default, this function supports a markdown like format where input newlines are only respected in some cases. This can be turned off to make `help` respect all newlines in the descriptions if desired.
Max width is also supported, which solves #28 (however, the caller needs to figure out the width of the tty).
=> New `help` api that provides options as to how paramters are printed.

clap.zig
Syncs with latest zig master version 0.10.0-dev.4117+54854e2ab
=> use builtin.Type instead of deprecated builtin.TypeInfo

clap.zig
toOwnedSlice() now returns an error union
=> Handle change to std.ArrayList(T).toOwnedSlice()

clap.zig
Rename `builtin.Struct.field_type` to `builtin.Struct.type`.
=> Update to latest Zig master

build.zig
With this change i was able to use clap with the new package manager.
In my package's build.zig:
```diff
diff --git a/build.zig b/build.zig
index 93e123d..54a38d6 100644
--- a/build.zig
+++ b/build.zig
+    const zig_clap_pkg = b.dependency("clap", .{
+        .target = target,
+        .optimize = optimize,
+    });
+    const zig_clap = zig_clap_pkg.module("clap");
const exe = b.addExecutable(.{ ... });
+    exe.addModule("zig-clap", zig_clap);
```
Note: before this patch, this change ^ resulted in an error. Something like 'can't find module clap'.
and my package's build.zig.zon:
```console
$ zig version
0.11.0-dev.1796+c9e02d3e6
$ cat build.zig.zon 
.{
.name = "mylib",
.version = "0.0.1",
.dependencies = .{
.clap = .{
.url = "https://github.com/travisstaloch/zig-clap/archive/refs/heads/ …
```
=> build: expose 'clap' module for dependeees

build.zig
This is necessary now that the API was changed in https://github.com/ziglang/zig/pull/14785.
Now that `b.addModule()` returns a `*Module`, we can reuse it as discussed [here](https://github.com/Hejsil/zig-clap/pull/92#issuecomment-1445353656)
=> build: use new addModule() API which now returns a Module

README.md, clap.zig, example/README.md.template, example/help.zig, example/simple-ex.zig, example/simple.zig, example/usage.zig
A flag with takes_value = .count will have an integer value which is the number of times it was specified in the arguments.  This is useful for repeatable flags, as is common for a -v/--verbose or -d/--debug flag to increase logging output.
=> Count occurrences of flags (was "Add .count type for flags")

clap.zig
Add support for multiple positional parameters - display such parameters correctly in the help and usage messages.
Adds unit tests for the help and usage message.
=> Support multiple positionals

build.zig
This makes a single change to the build.zig file to support zig 0.11.0-dev.4407+4d7dd1689, std.Build.addInstallArtifact() now takes a options struct which specifies where to put artifacts but the defaults are the same as before the change.
=> Update to latest zig (4d7dd1689)

README.md, clap.zig, example/help.zig, example/simple-ex.zig, example/simple.zig, example/usage.zig
=> Remove the default allocator from `ParseOptions`

clap.zig, clap/codepoint_counting_writer.zig, clap/parsers.zig
A complete solution would be to count the display-width of grapheme clusters, but that would require adding a dependency on something like zg, which is quite heavy (the library is great, Unicode is just complex).
Counting codepoints will ensure that typical non-ASCII text is supported, at least, but you can still throw it off with more complex Unicode constructions, which might not be so useful in help text anyway.
I also made a commit for compatibility with current Zig.
=> Count codepoints instead of bytes, when determining width

clap/parsers.zig
In order to get the more precise `ParseIntError.InvalidCharacter` error instead of `ParseIntError.Overflow` when a negative number is passed to a usize, uX typed argument, I use the `fmt.parseUnsigned` function.
=> fix: add uint parsing function

README.md, example/README.md.template, example/simple-ex.zig, example/simple.zig, example/streaming-clap.zig, example/subcommands.zig
Just noticed "none positional" instead of "non-positional" when reading the README (btw, at time of writing, the autodoc at the link isn't working, just letting you know) and decided to make a quick 10 min PR patching it specifically as well as some other things up.
=> Patch up README and fix comments in example files.

.github/workflows/docs.yml
Hopefully, the new `deploy-pages` version fixes the detection of uploaded artifact.
=> chore: bump deploy-pages action version

README.md, clap.zig, example/help.zig, example/simple-ex.zig, example/simple.zig, example/subcommands.zig, example/usage.zig
=> Incompatibility with latest Zig: ArrayList API change Fixes #165

README.md
This PR fixes the `usage` example and cleans up a few small typos.
- Use `clap.usageToFile(.stdout(), clap.Help, &params)` in the `usage` example.
- Minor documentation fixes:
- typos:
- `Diagnostics` → `Diagnostic`
- `postionals` → `positionals`
- grammar: "does not" → "do not" (plural subject)
- article: "an `value`" → "a `value`"
=> Fix `usage` example (`usageToFile`) and tidy typos
